### ISSUE TITLE
Index Error?

### ISSUE THREAD

**Issue by kjgenevieve** [learn-co-curriculum/programming-univbasics-4-array-concept-review#3]
It says, "If the Shark family had a new baby shark we would put her in index 1 and move all the other sharks up one."

Shouldn't it be **index 0**?

**Comment by sgharms** [comment]
@kjgenevieve 

In _this_ particular lesson, we're trying to not being up that particular complexity (indexing at zero). 

That's why we have this paragraph in the [Example Data section](https://github.com/learn-co-curriculum/programming-univbasics-4-array-concept-review#example-data):

> To keep things simple, we'll express this list in English, not in any programming language. In English, we tend to start numbering (or indexing) at 1, not 0, but the reverse is true in the programming world.

Is there something we could do to make this more clear?

**Comment by sgharms** [comment]
@kjgenevieve We've not heard back in a few days. As such, I'm going to close this issue. If you want to resume a discussion on this, please re-open. Thanks! 💙
